### ISSUE TITLE
CSS library choice

### ISSUE THREAD

**Issue by JiejayLan** [Kaihchen1230/csc47300Project#22]
We have a lot of choices, the most popular two are react-bootstrap, material-UI. We should use only one css library, instead of mixing them together

**Comment by albert6051** [comment]
I will have my vote on react-bootstrap. Since professor use it in his example, and we have used in our hw for address book. However, if you guys think material-UI will be a better choice, I will be fine too.

**Comment by srajan-17** [comment]
I'd prefer react-bootstrap, since we had some familiarity with it making the address book.

**Comment by JiejayLan** [comment]
I would say, the way how we use different css library is the same(npm install then import the component you need. If you know how to use reactBoostrap, you will get to know how to use material UI in 5 minutes). The only different is looks like now material UI is the most popular one and provide more components.

**Comment by albert6051** [comment]
Interesting, if we can use material-UI the same way we use reactBoostrap and it does provide more components for us to use, I think we should use it too.
